#!/bin/bash

docker exec -e CORE_PEER_ADDRESS=peer0.orghouse.house.com:7051 -e CORE_PEER_LOCALMSPID=OrgHouseMSP -e CORE_PEER_TLS_ENABLED=true -e CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/orghouse.house.com/peers/peer0.orghouse.house.com/tls/server.crt -e CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/orghouse.house.com/peers/peer0.orghouse.house.com/tls/server.key -e CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/orghouse.house.com/peers/peer0.orghouse.house.com/tls/ca.crt -e CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/orghouse.house.com/users/Admin@orghouse.house.com/msp cli peer chaincode invoke -n house -C house -c '{"args":["addHouseInfo","r1","h1","Mary","2019-01-01","100","Live","false"]}' --peerAddresses peer0.orghouse.house.com:7051 --tlsRootCertFiles /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/orghouse.house.com/peers/peer0.orghouse.house.com/tls/ca.crt -o orderer1.house.com:8050 --tls --cafile /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/house.com/orderers/orderer1.house.com/msp/tlscacerts/tlsca.house.com-cert.pem
sleep 10

docker exec -e CORE_PEER_ADDRESS=peer0.orgarea.house.com:9051 -e CORE_PEER_LOCALMSPID=OrgAreaMSP -e CORE_PEER_TLS_ENABLED=true -e CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/orgarea.house.com/peers/peer0.orgarea.house.com/tls/server.crt -e CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/orgarea.house.com/peers/peer0.orgarea.house.com/tls/server.key -e CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/orgarea.house.com/peers/peer0.orgarea.house.com/tls/ca.crt -e CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/orgarea.house.com/users/Admin@orgarea.house.com/msp cli peer chaincode invoke -n area -C area -c '{"args":["addAreaInfo","r1","a1","Ho Chi Minh","56","Tom","100"]}' --peerAddresses peer0.orgarea.house.com:9051 --tlsRootCertFiles /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/orgarea.house.com/peers/peer0.orgarea.house.com/tls/ca.crt -o orderer0.house.com:7050 --tls --cafile /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/house.com/orderers/orderer0.house.com/msp/tlscacerts/tlsca.house.com-cert.pem
sleep 10

docker exec -e CORE_PEER_ADDRESS=peer0.orgorder.house.com:11051 -e CORE_PEER_LOCALMSPID=OrgOrderMSP -e CORE_PEER_TLS_ENABLED=true -e CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/orgorder.house.com/peers/peer0.orgorder.house.com/tls/server.crt -e CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/orgorder.house.com/peers/peer0.orgorder.house.com/tls/server.key -e CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/orgorder.house.com/peers/peer0.orgorder.house.com/tls/ca.crt -e CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/orgorder.house.com/users/Admin@orgorder.house.com/msp cli peer chaincode invoke -n order -C order -c '{"args":["addOrderInfo","r1","ha1","o1","rr1","1000","2019-01-10","2019-01-20","discount"]}' --peerAddresses peer0.orgorder.house.com:11051 --tlsRootCertFiles /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/orgorder.house.com/peers/peer0.orgorder.house.com/tls/ca.crt -o orderer1.house.com:8050 --tls --cafile /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/house.com/orderers/orderer1.house.com/msp/tlscacerts/tlsca.house.com-cert.pem
sleep 10

docker exec -e CORE_PEER_ADDRESS=peer0.orgorder.house.com:11051 -e CORE_PEER_LOCALMSPID=OrgOrderMSP -e CORE_PEER_TLS_ENABLED=true -e CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/orgorder.house.com/peers/peer0.orgorder.house.com/tls/server.crt -e CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/orgorder.house.com/peers/peer0.orgorder.house.com/tls/server.key -e CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/orgorder.house.com/peers/peer0.orgorder.house.com/tls/ca.crt -e CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/orgorder.house.com/users/Admin@orgorder.house.com/msp cli peer chaincode invoke -n order -C order -c '{"args":["addOrderInfo","r1","ha2","o2","rr1","200","2019-01-25","2019-01-26","discount"]}' --peerAddresses peer0.orgorder.house.com:11051 --tlsRootCertFiles /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/orgorder.house.com/peers/peer0.orgorder.house.com/tls/ca.crt -o orderer0.house.com:7050 --tls --cafile /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/house.com/orderers/orderer0.house.com/msp/tlscacerts/tlsca.house.com-cert.pem
sleep 10

 docker exec -e CORE_PEER_ADDRESS=peer0.orghouse.house.com:7051 -e CORE_PEER_LOCALMSPID=OrgHouseMSP -e CORE_PEER_TLS_ENABLED=true -e CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/orghouse.house.com/peers/peer0.orghouse.house.com/tls/server.crt -e CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/orghouse.house.com/peers/peer0.orghouse.house.com/tls/server.key -e CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/orghouse.house.com/peers/peer0.orghouse.house.com/tls/ca.crt -e CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/orghouse.house.com/users/Admin@orghouse.house.com/msp cli peer chaincode query -n house -C house -c '{"args":["getHouseInfo","r1"]}'

docker exec -e CORE_PEER_ADDRESS=peer0.orgarea.house.com:9051 -e CORE_PEER_LOCALMSPID=OrgAreaMSP -e CORE_PEER_TLS_ENABLED=true -e CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/orgarea.house.com/peers/peer0.orgarea.house.com/tls/server.crt -e CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/orgarea.house.com/peers/peer0.orgarea.house.com/tls/server.key -e CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/orgarea.house.com/peers/peer0.orgarea.house.com/tls/ca.crt -e CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/orgarea.house.com/users/Admin@orgarea.house.com/msp cli peer chaincode query -n area -C area -c '{"args":["getAreaInfo","r1"]}'

docker exec -e CORE_PEER_ADDRESS=peer0.orgorder.house.com:11051 -e CORE_PEER_LOCALMSPID=OrgOrderMSP -e CORE_PEER_TLS_ENABLED=true -e CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/orgorder.house.com/peers/peer0.orgorder.house.com/tls/server.crt -e CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/orgorder.house.com/peers/peer0.orgorder.house.com/tls/server.key -e CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/orgorder.house.com/peers/peer0.orgorder.house.com/tls/ca.crt -e CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/orgorder.house.com/users/Admin@orgorder.house.com/msp cli peer chaincode query -n order -C order -c '{"args":["getOrderInfo","r1"]}'
